project:
  type: website
  output-dir: docs
  resources:
    - "*.pdf"

website:
  title: "Caleb Skinner"
  favicon: favicon.png
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching and Mentorship
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/CalebSkinner1
      - icon: linkedin
        href: https://www.linkedin.com/in/calebskinner1
  page-footer:
    center: "Last updated August 2026"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false

editor: source