---
title: "Projects"
---

Here are a brief list of some projects I have worked on recently.

### Working Papers

**Skinner, C.; Li, Meng (2025), "Exact Partial Constancy Prior for Structured Ensemble Forecasting"**

-   Proposes a widely applicable exact partial constancy prior for a principled Bayesian approach to forecast aggregation and ensemble learning. We design an efficient Markov Chain Monte Carlo algorithm explore the posterior model space and establish asymptotic consistency guarantees. Our simulations and applications to expert forecasts of unemployment rate and treasury bill rate demonstrate the proposed methods' gain over competing methods.

### Publications

**Skinner, C.; Sturdivant, R. (2024), “Is Momentum Real: On the Existence and Influences of Psychological Momentum in Tennis"**

-   Undergraduate Thesis measuring and analyzing psychological momentum under the direction of Dr. Rodney Sturdivant. Defining momentum as the backward approximation of the derivative of the players’ smoothed point margin curve, we find that a player’s momentum entering a point has a significant impact on his or her likelihood of winning the next point. You can find the full document [here](https://github.com/CalebSkinner1/TennisMomentum).

**Skinner, C, Patrick, J, Bryson, C. & Sturdivant, R. (2025, June 16). Mixed Martial Arts - Interrater Reliability. "The SCORE Network."** [https://doi.org/10.17605/OSF.IO/F8VBQ](https://doi.org/10.17605/OSF.IO/F8VBQ)

- SCORE Network Interactive lesson plan explaining Interrater Reliability using applications to Mixed Martial Arts.

### Other Research Projects

[**Detecting Presence of Brain Aneurysms**](https://github.com/CalebSkinner1/Detecting-Presence-of-Brain-Aneurysms) **(2025)**
-   Develop a deep learning pipeline for identification and localization of brain aneurysms from three-dimensional brain scans. Pre-processed multi-modal scans and implemented a two-step 3-D Convolutional Neural Network with modern block architecture.

**Sparse Trustworthy Variational Bayes (2025)**

-   Implemented a novel extension of Trustworthy Variational Bayes (Liu and Li, 2024) applied to the discrete spike-and-slab prior (Ray and Szabo, 2022) to address variance underestimation and improve variational credible intervals coverage.

[**Model Averaged Doubly Robust Estimator**](https://github.com/CalebSkinner1/ModelAveragedDR) **(2025)**

-   Compared the Model Averaged Doubly Robust Estimator (Cefalu et al., 2017) with competing methods like stepwise model selection and Bayesian Adjustment for Confounding (Wang et al., 2012) in a three-part simulation study.

**Sleeper Bayesian (2024)**

-   Developed a Normal Bayesian Hierarchical Model to estimate NBA player performance and future outcomes. Incorporated Game Theory decision boundaries to optimize fantasy basketball roster decisions. This work is ongoing.

**Sports Analytics Club – Vice President (2021-2023)**

-   Collaborated with Statistics PhD student Ryan Hebdon to develop a website (with R’s ShinyApp) filled with interactive visualizations and tables utilized by Baylor baseball’s staff.

[**Global Health Survey**](https://github.com/CalebSkinner1/GlobalHealthSurvey) **(2021-2022)**

-   Produced \~50 pages of visualizations and statistical analysis for a research paper assessing the opinions of Global Health among undergraduate students.

**Football Analytics Blitz (2022)**

-   Analyzed NFL data from 2021 to create a comprehensive game-strategy in Syracuse University’s case competition. Produced visualizations justifying decisions and presented conclusions to a panel of judges.
